"""create tasks table

Revision ID: 828b57cfa4d1
Revises: 3a6ae4c7bc5a
Create Date: 2026-01-04 00:20:54.454115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828b57cfa4d1'
down_revision: Union[str, Sequence[str], None] = '3a6ae4c7bc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
